apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bad-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: bad-backend
    servicePort: 60001
---
apiVersion: v1
kind: Service
metadata:
 name: bad-backend
spec:
  type: NodePort
  ports:
  - port: 60001
    targetPort: 443
